export const VOLUNTEER_LIST_REQUEST = 'VOLUNTEER_LIST_REQUEST';
export const VOLUNTEER_LIST_SUCCESS = 'VOLUNTEER_LIST_SUCCESS';
export const VOLUNTEER_LIST_FAIL = 'VOLUNTEER_LIST_FAIL';


export const VOLUNTEER_CREATE_REQUEST = 'VOLUNTEER_CREATE_REQUEST';
export const VOLUNTEER_CREATE_SUCCESS = 'VOLUNTEER_CREATE_SUCCESS';
export const VOLUNTEER_CREATE_FAIL = 'VOLUNTEER_CREATE_FAIL';

export const VOLUNTEER_DELETE_REQUEST = 'VOLUNTEER_DELETE_REQUEST';
export const VOLUNTEER_DELETE_SUCCESS = 'VOLUNTEER_DELETE_SUCCESS';
export const VOLUNTEER_DELETE_FAIL = 'VOLUNTEER_DELETE_FAIL';
