export const VOLUNTEER_LIST_REQUEST = 'VOLUNTEER_LIST_REQUEST';
export const VOLUNTEER_LIST_SUCCESS = 'VOLUNTEER_LIST_SUCCESS';
export const VOLUNTEER_LIST_FAIL = 'VOLUNTEER_LIST_FAIL';


export const VOLUNTEER_CREATE_REQUEST = 'VOLUNTEER_CREATE_REQUEST';
export const VOLUNTEER_CREATE_SUCCESS = 'VOLUNTEER_CREATE_SUCCESS';
export const VOLUNTEER_CREATE_FAIL = 'VOLUNTEER_CREATE_FAIL';

export const VOLUNTEER_DETAILS_REQUEST = 'VOLUNTEER_DETAILS_REQUEST';
export const VOLUNTEER_DETAILS_SUCCESS = 'VOLUNTEER_DETAILS_SUCCESS';
export const VOLUNTEER_DETAILS_FAIL = 'VOLUNTEER_DETAILS_FAIL';
